---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    theme: flatly
---

```{r setup, include=FALSE}
library(tidyverse)
library(plotly)
library(p8105.datasets)
library(flexdashboard)
library(viridis)
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_bw() + theme(legend.position = "bottom"))
## Chart A

avg_score_street = 
  rest_inspec %>%
  group_by(street) %>%
  mutate(avg_score = mean(score)) %>%
  drop_na()

avg_score_street

##Chart B
critical_manhattan = 
  rest_inspec %>%
  select(-action) %>%
  filter(critical_flag == "Critical") %>%
  drop_na()

critical_manhattan

##Chart C
italian_scores = 
  rest_inspec %>%
  drop_na() %>%
  filter(str_detect(cuisine_description, "[I,i]talian")) %>%
  group_by(grade_date) %>%
  mutate(avg_score = mean(score))

italian_scores

```

Column {data-width=450}
-----------------------------------------------------------------------

### Chart A: Average Score Per Street Name

```{r, echo = FALSE}
  
avg_score_street %>%
  mutate(text_label = str_c("Street Name: ", street, '\nAvg Score: ', avg_score)) %>%
  plot_ly(
    x = ~street,
    y = ~avg_score,
    color = ~zipcode,
    colors = viridis_pal(option = "C")(3),
    type = "scatter",
    mode = "markers",
    text = ~text_label,
    alpha = 0.5
  ) 

```

Column {data-width=450}
-----------------------------------------------------------------------

### Chart B: Distribution of Scores and Grades in Critically Flagged Restaurants

```{r, echo = FALSE}

critical_manhattan %>%
  mutate(grade = forcats::fct_relevel(grade, c("A", "B", "C", "P", "Z", "Not Yet Graded"))) %>%
  plot_ly(
    x = ~grade,
    y = ~score,
    color = ~grade,
    colors = viridis_pal(option = "D")(3),
    type = "box",
    alpha = 0.5
  ) 
```

Column {data-width=450}
-----------------------------------------------------------------------
### Chart C: Average Italian Restaurant Scores by Grade Date

```{r, echo = FALSE}
italian_scores %>%
  mutate(text_label = str_c("Grade Date: ", grade_date, '\nGrade: ', grade, '\nAverage Score: ', avg_score)) %>%
plot_ly(
        x = ~grade_date,
        y = ~avg_score,
        color = ~grade,
        colors = viridis_pal(option = "D")(3),
        type = "bar",
        text = ~text_label)
```