---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(plotly)
library(p8105.datasets)
library(viridis)
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_bw() + theme(legend.position = "bottom"))


data("rest_inspec")

rest_inspec = 
  rest_inspec%>%
  janitor::clean_names() %>%
  mutate(boro = str_to_lower(boro)) %>%
  filter(inspection_date != "01/01/1900") %>%
  drop_na()
  
## Chart A

score_street = 
  rest_inspec %>%
  group_by(zipcode) %>%
  filter(cuisine_description == "Seafood" & boro == "manhattan") %>%
  filter(str_detect(inspection_date,"2017")) 

score_street

##Chart B
critical_pizza_queens = 
  rest_inspec %>%
  filter(critical_flag == "Critical" & 
           boro == "queens" & 
           cuisine_description == "Pizza") %>%
  filter(str_detect(inspection_date,"2016")) 

critical_pizza_queens

##Chart C
italian_scores = 
  rest_inspec %>%
  filter(str_detect(action, "re-opened") & cuisine_description == "Italian") %>%
  group_by(grade_date) %>%
  filter(str_detect(grade_date, "2017"))

italian_scores

```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A: Distribution of Scores of Manhattan Seafood Restaurants by Zipcode in 2017

```{r, echo = FALSE}
score_street %>%
  mutate(text_label = str_c("Name: ", dba, 
                            '\nScore: ', score)) %>%
  plot_ly(
    x = ~zipcode,
    y = ~score,
    color = ~grade,
    colors = viridis_pal(option = "C")(3),
    type = "scatter",
    mode = "markers",
    text = ~text_label,
    alpha = 0.5
  ) 
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B: Distribution of Scores in Queens Pizza Restaurants in 2017

```{r, echo = FALSE}
critical_pizza_queens %>%
  mutate(grade = forcats::fct_relevel(grade, c("A", "B", "C", "P", "Z", "Not Yet Graded"))) %>%
  plot_ly(
    x = ~grade,
    y = ~score,
    color = ~grade,
    colors = viridis_pal(option = "D")(3),
    type = "box",
    alpha = 0.5
  ) 
```

### Chart C: Re-Opened Italian Restaurant Scores in 2017

```{r, echo = FALSE}
italian_scores %>%
  mutate(text_label = str_c("Name: ", dba, 
                            '\nGrade Date: ', grade_date,
                            '\nGrade: ', grade, 
                            '\nFlag: ', critical_flag)) %>%
plot_ly(x = ~inspection_date,
        y = ~score,
        color = ~grade,
        colors = viridis_pal(option = "D")(3),
        type = "bar",
        text = ~text_label)
```

